apiVersion: v1
kind: Service
metadata:
  labels:
    app: chat-server-example
  name: chat-server
spec:
  ports:
  - name: 3000-tcp
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: chat-server-example
    deploymentconfig: chat-server-example
  sessionAffinity: None
  type: ClusterIP

